// Code generated by protoc-gen-go. DO NOT EDIT.
// source: jwtrpcdeclare.proto

package jwtrpcdeclare

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatusData_Status int32

const (
	StatusData_SUCCEED StatusData_Status = 0
	StatusData_ERROR   StatusData_Status = 1
)

var StatusData_Status_name = map[int32]string{
	0: "SUCCEED",
	1: "ERROR",
}

var StatusData_Status_value = map[string]int32{
	"SUCCEED": 0,
	"ERROR":   1,
}

func (x StatusData_Status) String() string {
	return proto.EnumName(StatusData_Status_name, int32(x))
}

func (StatusData_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_de98355277429ad0, []int{2, 0}
}

type SignRequest struct {
	Jsondata             []byte   `protobuf:"bytes,1,opt,name=jsondata,proto3" json:"jsondata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignRequest) Reset()         { *m = SignRequest{} }
func (m *SignRequest) String() string { return proto.CompactTextString(m) }
func (*SignRequest) ProtoMessage()    {}
func (*SignRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_de98355277429ad0, []int{0}
}

func (m *SignRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignRequest.Unmarshal(m, b)
}
func (m *SignRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignRequest.Marshal(b, m, deterministic)
}
func (m *SignRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignRequest.Merge(m, src)
}
func (m *SignRequest) XXX_Size() int {
	return xxx_messageInfo_SignRequest.Size(m)
}
func (m *SignRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignRequest proto.InternalMessageInfo

func (m *SignRequest) GetJsondata() []byte {
	if m != nil {
		return m.Jsondata
	}
	return nil
}

type VerifyRequest struct {
	Tokendata            []byte   `protobuf:"bytes,1,opt,name=tokendata,proto3" json:"tokendata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyRequest) Reset()         { *m = VerifyRequest{} }
func (m *VerifyRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyRequest) ProtoMessage()    {}
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_de98355277429ad0, []int{1}
}

func (m *VerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyRequest.Unmarshal(m, b)
}
func (m *VerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyRequest.Marshal(b, m, deterministic)
}
func (m *VerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyRequest.Merge(m, src)
}
func (m *VerifyRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyRequest.Size(m)
}
func (m *VerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyRequest proto.InternalMessageInfo

func (m *VerifyRequest) GetTokendata() []byte {
	if m != nil {
		return m.Tokendata
	}
	return nil
}

type StatusData struct {
	Status               StatusData_Status `protobuf:"varint,1,opt,name=status,proto3,enum=jwtrpcdeclare.StatusData_Status" json:"status,omitempty"`
	Msg                  string            `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *StatusData) Reset()         { *m = StatusData{} }
func (m *StatusData) String() string { return proto.CompactTextString(m) }
func (*StatusData) ProtoMessage()    {}
func (*StatusData) Descriptor() ([]byte, []int) {
	return fileDescriptor_de98355277429ad0, []int{2}
}

func (m *StatusData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusData.Unmarshal(m, b)
}
func (m *StatusData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusData.Marshal(b, m, deterministic)
}
func (m *StatusData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusData.Merge(m, src)
}
func (m *StatusData) XXX_Size() int {
	return xxx_messageInfo_StatusData.Size(m)
}
func (m *StatusData) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusData.DiscardUnknown(m)
}

var xxx_messageInfo_StatusData proto.InternalMessageInfo

func (m *StatusData) GetStatus() StatusData_Status {
	if m != nil {
		return m.Status
	}
	return StatusData_SUCCEED
}

func (m *StatusData) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type SignResponse struct {
	Status               *StatusData `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data                 string      `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SignResponse) Reset()         { *m = SignResponse{} }
func (m *SignResponse) String() string { return proto.CompactTextString(m) }
func (*SignResponse) ProtoMessage()    {}
func (*SignResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_de98355277429ad0, []int{3}
}

func (m *SignResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignResponse.Unmarshal(m, b)
}
func (m *SignResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignResponse.Marshal(b, m, deterministic)
}
func (m *SignResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignResponse.Merge(m, src)
}
func (m *SignResponse) XXX_Size() int {
	return xxx_messageInfo_SignResponse.Size(m)
}
func (m *SignResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignResponse proto.InternalMessageInfo

func (m *SignResponse) GetStatus() *StatusData {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SignResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type VerifyResponse struct {
	Status               *StatusData `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data                 []byte      `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *VerifyResponse) Reset()         { *m = VerifyResponse{} }
func (m *VerifyResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyResponse) ProtoMessage()    {}
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_de98355277429ad0, []int{4}
}

func (m *VerifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyResponse.Unmarshal(m, b)
}
func (m *VerifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyResponse.Marshal(b, m, deterministic)
}
func (m *VerifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyResponse.Merge(m, src)
}
func (m *VerifyResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyResponse.Size(m)
}
func (m *VerifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyResponse proto.InternalMessageInfo

func (m *VerifyResponse) GetStatus() *StatusData {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *VerifyResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("jwtrpcdeclare.StatusData_Status", StatusData_Status_name, StatusData_Status_value)
	proto.RegisterType((*SignRequest)(nil), "jwtrpcdeclare.SignRequest")
	proto.RegisterType((*VerifyRequest)(nil), "jwtrpcdeclare.VerifyRequest")
	proto.RegisterType((*StatusData)(nil), "jwtrpcdeclare.StatusData")
	proto.RegisterType((*SignResponse)(nil), "jwtrpcdeclare.SignResponse")
	proto.RegisterType((*VerifyResponse)(nil), "jwtrpcdeclare.VerifyResponse")
}

func init() { proto.RegisterFile("jwtrpcdeclare.proto", fileDescriptor_de98355277429ad0) }

var fileDescriptor_de98355277429ad0 = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x41, 0x4f, 0xc2, 0x40,
	0x10, 0x85, 0xa9, 0x62, 0xb5, 0xd3, 0x42, 0x9a, 0xf1, 0x82, 0x15, 0x93, 0x66, 0x4f, 0x78, 0x90,
	0xc4, 0x7a, 0xf1, 0x6a, 0xa0, 0x31, 0xf1, 0x62, 0xb2, 0x0d, 0x7a, 0x5e, 0xcb, 0x4a, 0x8a, 0xda,
	0xd6, 0xdd, 0x45, 0xa2, 0xbf, 0xc4, 0x9f, 0x6b, 0xd8, 0xa5, 0xd4, 0x12, 0xb9, 0x79, 0x9b, 0x9d,
	0xf9, 0xf2, 0xde, 0x9b, 0x4e, 0xe1, 0x78, 0xbe, 0x54, 0xa2, 0x4c, 0xa7, 0x3c, 0x7d, 0x65, 0x82,
	0x0f, 0x4b, 0x51, 0xa8, 0x02, 0x3b, 0x8d, 0x26, 0x39, 0x07, 0x37, 0xc9, 0x66, 0x39, 0xe5, 0xef,
	0x0b, 0x2e, 0x15, 0x06, 0x70, 0x34, 0x97, 0x45, 0x3e, 0x65, 0x8a, 0xf5, 0xac, 0xd0, 0x1a, 0x78,
	0x74, 0xf3, 0x26, 0x17, 0xd0, 0x79, 0xe0, 0x22, 0x7b, 0xfe, 0xac, 0xe0, 0x3e, 0x38, 0xaa, 0x78,
	0xe1, 0xbf, 0xe9, 0xba, 0x41, 0xbe, 0x00, 0x12, 0xc5, 0xd4, 0x42, 0x8e, 0x99, 0x62, 0x78, 0x0d,
	0xb6, 0xd4, 0x2f, 0x0d, 0x76, 0xa3, 0x70, 0xd8, 0x0c, 0x57, 0xa3, 0xeb, 0x92, 0xae, 0x79, 0xf4,
	0x61, 0xff, 0x4d, 0xce, 0x7a, 0x7b, 0xa1, 0x35, 0x70, 0xe8, 0xaa, 0x24, 0x21, 0xd8, 0x86, 0x41,
	0x17, 0x0e, 0x93, 0xc9, 0x68, 0x14, 0xc7, 0x63, 0xbf, 0x85, 0x0e, 0x1c, 0xc4, 0x94, 0xde, 0x53,
	0xdf, 0x22, 0x13, 0xf0, 0xcc, 0x56, 0xb2, 0x2c, 0x72, 0xc9, 0xf1, 0xb2, 0xe1, 0xee, 0x46, 0x27,
	0x3b, 0xdd, 0x37, 0xb6, 0x08, 0x6d, 0xbd, 0x97, 0xf1, 0xd5, 0x35, 0x79, 0x84, 0x6e, 0xf5, 0x05,
	0xfe, 0x47, 0xd8, 0x33, 0xc2, 0xd1, 0xb7, 0x05, 0x70, 0xb7, 0x54, 0x09, 0x17, 0x1f, 0x59, 0xca,
	0xf1, 0x06, 0xda, 0xab, 0xf8, 0x18, 0x6c, 0xab, 0xd5, 0x97, 0x0a, 0x4e, 0xff, 0x9c, 0x99, 0x58,
	0xa4, 0x85, 0xb7, 0x60, 0x9b, 0xa8, 0xd8, 0xdf, 0x02, 0x1b, 0x37, 0x0c, 0xce, 0x76, 0x4c, 0x2b,
	0xa1, 0x27, 0x5b, 0xff, 0x36, 0x57, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x54, 0x77, 0x75,
	0x4d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// JwtServiceClient is the client API for JwtService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JwtServiceClient interface {
	Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error)
	Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error)
}

type jwtServiceClient struct {
	cc *grpc.ClientConn
}

func NewJwtServiceClient(cc *grpc.ClientConn) JwtServiceClient {
	return &jwtServiceClient{cc}
}

func (c *jwtServiceClient) Sign(ctx context.Context, in *SignRequest, opts ...grpc.CallOption) (*SignResponse, error) {
	out := new(SignResponse)
	err := c.cc.Invoke(ctx, "/jwtrpcdeclare.JwtService/Sign", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jwtServiceClient) Verify(ctx context.Context, in *VerifyRequest, opts ...grpc.CallOption) (*VerifyResponse, error) {
	out := new(VerifyResponse)
	err := c.cc.Invoke(ctx, "/jwtrpcdeclare.JwtService/Verify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JwtServiceServer is the server API for JwtService service.
type JwtServiceServer interface {
	Sign(context.Context, *SignRequest) (*SignResponse, error)
	Verify(context.Context, *VerifyRequest) (*VerifyResponse, error)
}

// UnimplementedJwtServiceServer can be embedded to have forward compatible implementations.
type UnimplementedJwtServiceServer struct {
}

func (*UnimplementedJwtServiceServer) Sign(ctx context.Context, req *SignRequest) (*SignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sign not implemented")
}
func (*UnimplementedJwtServiceServer) Verify(ctx context.Context, req *VerifyRequest) (*VerifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Verify not implemented")
}

func RegisterJwtServiceServer(s *grpc.Server, srv JwtServiceServer) {
	s.RegisterService(&_JwtService_serviceDesc, srv)
}

func _JwtService_Sign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JwtServiceServer).Sign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jwtrpcdeclare.JwtService/Sign",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JwtServiceServer).Sign(ctx, req.(*SignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JwtService_Verify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JwtServiceServer).Verify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/jwtrpcdeclare.JwtService/Verify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JwtServiceServer).Verify(ctx, req.(*VerifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _JwtService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "jwtrpcdeclare.JwtService",
	HandlerType: (*JwtServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sign",
			Handler:    _JwtService_Sign_Handler,
		},
		{
			MethodName: "Verify",
			Handler:    _JwtService_Verify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jwtrpcdeclare.proto",
}
