// Code generated by protoc-gen-go. DO NOT EDIT.
// source: jwtrpcdeclare.proto

package jwtrpcdeclare

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Algo int32

const (
	Algo_HASH Algo = 0
	Algo_RSA  Algo = 1
)

var Algo_name = map[int32]string{
	0: "HASH",
	1: "RSA",
}

var Algo_value = map[string]int32{
	"HASH": 0,
	"RSA":  1,
}

func (x Algo) String() string {
	return proto.EnumName(Algo_name, int32(x))
}

func (Algo) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_de98355277429ad0, []int{0}
}

type StatusData_Status int32

const (
	StatusData_SUCCEED StatusData_Status = 0
	StatusData_ERROR   StatusData_Status = 1
)

var StatusData_Status_name = map[int32]string{
	0: "SUCCEED",
	1: "ERROR",
}

var StatusData_Status_value = map[string]int32{
	"SUCCEED": 0,
	"ERROR":   1,
}

func (x StatusData_Status) String() string {
	return proto.EnumName(StatusData_Status_name, int32(x))
}

func (StatusData_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_de98355277429ad0, []int{2, 0}
}

type SignJSONRequest struct {
	Algo                 Algo     `protobuf:"varint,1,opt,name=algo,proto3,enum=jwtrpcdeclare.Algo" json:"algo,omitempty"`
	Payload              string   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Aud                  string   `protobuf:"bytes,3,opt,name=aud,proto3" json:"aud,omitempty"`
	Iss                  string   `protobuf:"bytes,4,opt,name=iss,proto3" json:"iss,omitempty"`
	Exp                  int64    `protobuf:"varint,5,opt,name=exp,proto3" json:"exp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignJSONRequest) Reset()         { *m = SignJSONRequest{} }
func (m *SignJSONRequest) String() string { return proto.CompactTextString(m) }
func (*SignJSONRequest) ProtoMessage()    {}
func (*SignJSONRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_de98355277429ad0, []int{0}
}

func (m *SignJSONRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignJSONRequest.Unmarshal(m, b)
}
func (m *SignJSONRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignJSONRequest.Marshal(b, m, deterministic)
}
func (m *SignJSONRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignJSONRequest.Merge(m, src)
}
func (m *SignJSONRequest) XXX_Size() int {
	return xxx_messageInfo_SignJSONRequest.Size(m)
}
func (m *SignJSONRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignJSONRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignJSONRequest proto.InternalMessageInfo

func (m *SignJSONRequest) GetAlgo() Algo {
	if m != nil {
		return m.Algo
	}
	return Algo_HASH
}

func (m *SignJSONRequest) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func (m *SignJSONRequest) GetAud() string {
	if m != nil {
		return m.Aud
	}
	return ""
}

func (m *SignJSONRequest) GetIss() string {
	if m != nil {
		return m.Iss
	}
	return ""
}

func (m *SignJSONRequest) GetExp() int64 {
	if m != nil {
		return m.Exp
	}
	return 0
}

type VerifyRequest struct {
	Algo                 Algo     `protobuf:"varint,1,opt,name=algo,proto3,enum=jwtrpcdeclare.Algo" json:"algo,omitempty"`
	Tokendata            string   `protobuf:"bytes,2,opt,name=tokendata,proto3" json:"tokendata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyRequest) Reset()         { *m = VerifyRequest{} }
func (m *VerifyRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyRequest) ProtoMessage()    {}
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_de98355277429ad0, []int{1}
}

func (m *VerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyRequest.Unmarshal(m, b)
}
func (m *VerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyRequest.Marshal(b, m, deterministic)
}
func (m *VerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyRequest.Merge(m, src)
}
func (m *VerifyRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyRequest.Size(m)
}
func (m *VerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyRequest proto.InternalMessageInfo

func (m *VerifyRequest) GetAlgo() Algo {
	if m != nil {
		return m.Algo
	}
	return Algo_HASH
}

func (m *VerifyRequest) GetTokendata() string {
	if m != nil {
		return m.Tokendata
	}
	return ""
}

type StatusData struct {
	Status               StatusData_Status `protobuf:"varint,1,opt,name=status,proto3,enum=jwtrpcdeclare.StatusData_Status" json:"status,omitempty"`
	Msg                  string            `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *StatusData) Reset()         { *m = StatusData{} }
func (m *StatusData) String() string { return proto.CompactTextString(m) }
func (*StatusData) ProtoMessage()    {}
func (*StatusData) Descriptor() ([]byte, []int) {
	return fileDescriptor_de98355277429ad0, []int{2}
}

func (m *StatusData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusData.Unmarshal(m, b)
}
func (m *StatusData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusData.Marshal(b, m, deterministic)
}
func (m *StatusData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusData.Merge(m, src)
}
func (m *StatusData) XXX_Size() int {
	return xxx_messageInfo_StatusData.Size(m)
}
func (m *StatusData) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusData.DiscardUnknown(m)
}

var xxx_messageInfo_StatusData proto.InternalMessageInfo

func (m *StatusData) GetStatus() StatusData_Status {
	if m != nil {
		return m.Status
	}
	return StatusData_SUCCEED
}

func (m *StatusData) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type SignResponse struct {
	Status               *StatusData `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data                 string      `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SignResponse) Reset()         { *m = SignResponse{} }
func (m *SignResponse) String() string { return proto.CompactTextString(m) }
func (*SignResponse) ProtoMessage()    {}
func (*SignResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_de98355277429ad0, []int{3}
}

func (m *SignResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignResponse.Unmarshal(m, b)
}
func (m *SignResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignResponse.Marshal(b, m, deterministic)
}
func (m *SignResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignResponse.Merge(m, src)
}
func (m *SignResponse) XXX_Size() int {
	return xxx_messageInfo_SignResponse.Size(m)
}
func (m *SignResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignResponse proto.InternalMessageInfo

func (m *SignResponse) GetStatus() *StatusData {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *SignResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type VerifyJSONResponse struct {
	Status               *StatusData `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Data                 string      `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *VerifyJSONResponse) Reset()         { *m = VerifyJSONResponse{} }
func (m *VerifyJSONResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyJSONResponse) ProtoMessage()    {}
func (*VerifyJSONResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_de98355277429ad0, []int{4}
}

func (m *VerifyJSONResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyJSONResponse.Unmarshal(m, b)
}
func (m *VerifyJSONResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyJSONResponse.Marshal(b, m, deterministic)
}
func (m *VerifyJSONResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyJSONResponse.Merge(m, src)
}
func (m *VerifyJSONResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyJSONResponse.Size(m)
}
func (m *VerifyJSONResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyJSONResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyJSONResponse proto.InternalMessageInfo

func (m *VerifyJSONResponse) GetStatus() *StatusData {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *VerifyJSONResponse) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterEnum("jwtrpcdeclare.Algo", Algo_name, Algo_value)
	proto.RegisterEnum("jwtrpcdeclare.StatusData_Status", StatusData_Status_name, StatusData_Status_value)
	proto.RegisterType((*SignJSONRequest)(nil), "jwtrpcdeclare.SignJSONRequest")
	proto.RegisterType((*VerifyRequest)(nil), "jwtrpcdeclare.VerifyRequest")
	proto.RegisterType((*StatusData)(nil), "jwtrpcdeclare.StatusData")
	proto.RegisterType((*SignResponse)(nil), "jwtrpcdeclare.SignResponse")
	proto.RegisterType((*VerifyJSONResponse)(nil), "jwtrpcdeclare.VerifyJSONResponse")
}

func init() { proto.RegisterFile("jwtrpcdeclare.proto", fileDescriptor_de98355277429ad0) }

var fileDescriptor_de98355277429ad0 = []byte{
	// 379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4d, 0x8f, 0xda, 0x30,
	0x14, 0x8c, 0x9b, 0xf0, 0xf5, 0x28, 0x25, 0x7a, 0x5c, 0x02, 0x45, 0x55, 0xea, 0x4b, 0x51, 0x0f,
	0x48, 0xa5, 0x97, 0x5e, 0x29, 0x20, 0x51, 0x0e, 0x45, 0x72, 0x04, 0x87, 0xf6, 0xe4, 0x12, 0x37,
	0x4a, 0x9b, 0x92, 0x34, 0x36, 0xa5, 0xec, 0x4f, 0xd8, 0x5f, 0xb2, 0x3f, 0x73, 0xe5, 0x24, 0x2c,
	0x04, 0xb1, 0x87, 0x95, 0xf6, 0x36, 0x1e, 0x8f, 0xe6, 0x3d, 0x4f, 0x26, 0xd0, 0xf9, 0xb5, 0x57,
	0x69, 0xb2, 0xf1, 0xc5, 0x26, 0xe2, 0xa9, 0x18, 0x26, 0x69, 0xac, 0x62, 0x6c, 0x95, 0x48, 0x7a,
	0x4b, 0xa0, 0xed, 0x85, 0xc1, 0x76, 0xe1, 0x2d, 0xbf, 0x32, 0xf1, 0x77, 0x27, 0xa4, 0xc2, 0x77,
	0x60, 0xf1, 0x28, 0x88, 0x1d, 0xe2, 0x92, 0xc1, 0xab, 0x51, 0x67, 0x58, 0xb6, 0x19, 0x47, 0x41,
	0xcc, 0x32, 0x01, 0x3a, 0x50, 0x4b, 0xf8, 0x21, 0x8a, 0xb9, 0xef, 0xbc, 0x70, 0xc9, 0xa0, 0xc1,
	0x8e, 0x47, 0xb4, 0xc1, 0xe4, 0x3b, 0xdf, 0x31, 0x33, 0x56, 0x43, 0xcd, 0x84, 0x52, 0x3a, 0x56,
	0xce, 0x84, 0x52, 0x6a, 0x46, 0xfc, 0x4f, 0x9c, 0x8a, 0x4b, 0x06, 0x26, 0xd3, 0x90, 0xae, 0xa1,
	0xb5, 0x16, 0x69, 0xf8, 0xf3, 0xf0, 0xe4, 0x4d, 0xfa, 0xd0, 0x50, 0xf1, 0x6f, 0xb1, 0xf5, 0xb9,
	0xe2, 0xc5, 0x2e, 0x27, 0x82, 0xde, 0x00, 0x78, 0x8a, 0xab, 0x9d, 0x9c, 0x72, 0xc5, 0xf1, 0x13,
	0x54, 0x65, 0x76, 0x2a, 0x6c, 0xdd, 0x0b, 0xdb, 0x93, 0xb4, 0x80, 0xac, 0xd0, 0xeb, 0x8d, 0xff,
	0xc8, 0xa0, 0xf0, 0xd7, 0x90, 0xba, 0x50, 0xcd, 0x35, 0xd8, 0x84, 0x9a, 0xb7, 0x9a, 0x4c, 0x66,
	0xb3, 0xa9, 0x6d, 0x60, 0x03, 0x2a, 0x33, 0xc6, 0x96, 0xcc, 0x26, 0x74, 0x05, 0x2f, 0x75, 0xbe,
	0x4c, 0xc8, 0x24, 0xde, 0x4a, 0x81, 0x1f, 0x4a, 0xd3, 0x9b, 0xa3, 0xee, 0xa3, 0xd3, 0x1f, 0xc6,
	0x22, 0x58, 0x67, 0xef, 0xca, 0x30, 0xfd, 0x0e, 0x98, 0x47, 0x95, 0x7f, 0xb8, 0x67, 0x35, 0x7f,
	0xdf, 0x05, 0x4b, 0x67, 0x8b, 0x75, 0xb0, 0xe6, 0x63, 0x6f, 0x6e, 0x1b, 0x58, 0x03, 0x93, 0x79,
	0x63, 0x9b, 0x8c, 0xee, 0x08, 0xc0, 0x62, 0xaf, 0x3c, 0x91, 0xfe, 0x0b, 0x37, 0x02, 0xbf, 0x40,
	0xfd, 0xd8, 0x1e, 0x7c, 0x73, 0x39, 0xac, 0x5c, 0xab, 0xde, 0xeb, 0x2b, 0xf7, 0xc7, 0xcd, 0xa9,
	0x81, 0x4b, 0x80, 0xd3, 0x8b, 0xb0, 0x7f, 0x21, 0x2e, 0xf5, 0xa2, 0xf7, 0xf6, 0xea, 0xed, 0x79,
	0x14, 0xd4, 0xf8, 0xdc, 0xfe, 0x56, 0xee, 0xfa, 0x8f, 0x6a, 0xf6, 0x07, 0x7c, 0xbc, 0x0f, 0x00,
	0x00, 0xff, 0xff, 0x42, 0x44, 0xd8, 0x20, 0x18, 0x03, 0x00, 0x00,
}
